### ISSUE TITLE
https://dev.bulkgate.com/sms-campaign/active/id-bulkgate-064379#/running

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#263] opened 2021-01-19 13:16 UTC
![image](https://user-images.githubusercontent.com/70203691/105039432-d9a8a300-5a60-11eb-91a3-ec0919f8eaa2.png)
zarovnání na střed?

**Comment by MartinKreizl** [comment] 2021-01-25 15:20
Duplicate of #277

**Closed** 2021-01-25 17:25 UTC
Labels: duplicate
