### ISSUE TITLE
Nástěnka analytika

### ISSUE THREAD

**Issue by kubaanec1** [TOPefekt/BulkGate-issues#267] opened 2021-01-19 14:26 UTC
![image](https://user-images.githubusercontent.com/70203691/105047171-46746b00-5a6a-11eb-94e3-d5c32a3c91dd.png)
nečitelné

**Comment by MartinKreizl** [comment] 2021-01-25 15:00
Duplicate of #277

**Closed** 2021-01-25 17:25 UTC
Labels: duplicate
